src/khohang/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Nhanvien;
use App\Khachhang;
use App\Donhang;
use App\Sanpham;
use App\Chitietdonhang;
use App\Mail\OrderMailer;

use Illuminate\Support\Facades\DB;
Route::get('/', function () {
    return view('welcome');
});
Route::get('/admin/sanpham', 'SanPhamController@index')->name('backend.sanpham.index');
Route::get('/admin/sanpham/create', 'SanPhamController@create')->name('backend.sanpham.create');
Route::get('/admin/danhsachsanpham/print', 'SanPhamController@print')->name('danhsachsanpham.print');
Route::get('/admin/danhsachsanpham/excel', 'SanPhamController@excel')->name('danhsachsanpham.excel');
Route::get('/admin/danhsachsanpham/pdf', 'SanPhamController@pdf')->name('danhsachsanpham.pdf');

//QLdanh sách kho
Route::get('/admin/danhsachkho/index', 'KhoHangController@index')->name('danhsachkho.index');
Route::get('/admin/danhsachkho/create', 'KhoHangController@create')->name('danhsachkho.create');
//QLPhieu nk
Route::get('/admin/danhsachkho/nhapkho', 'KhoHangController@nhapkho')->name('danhsachkho.nhapkho');
Route::get('/admin/danhsachkho/{id}/xuatphieunhap', 'KhoHangController@xuatphieunhap')->name('danhsachkho.xuatphieunhap');
Route::get('/admin/danhsachkho/xuatpn', 'KhoHangController@infophieunhap')->name('danhsachkho.infophieunhap');

//QLPhieu xk
Route::get('/admin/danhsachkho/xuatkho', 'KhoHangController@xuatkho')->name('danhsachkho.xuatkho');
Route::get('/admin/danhsachkho/{id}/phieuxuatkho', 'KhoHangController@phieuxuatkho')->name('danhsachkho.phieuxuatkho');
Route::get('/admin/danhsachkho/xuatpx', 'KhoHangController@infophieuxuat')->name('danhsachkho.infophieuxuat');
Route::get('/admin/danhsachkho/baocaosoluong', 'KhoHangController@baocaosoluong')->name('danhsachkho.baocaosoluong');


Route::get('/', 'Frontend\FrontendController@index')->name('frontend.home');
Route::get('/gioi-thieu', 'Frontend\FrontendController@about')->name('frontend.about');
Route::get('/lien-he', 'Frontend\FrontendController@contact')->name('frontend.contact');
Route::get('/gop-y', 'Frontend\FrontendController@blog')->name('frontend.blog');
Route::get('/gop-y/goi-gop-y', 'Frontend\FrontendController@infoblog')->name('frontend.infoblog');
Route::post('/lien-he/goi-loi-nhan', 'Frontend\FrontendController@sendMailContactForm')->name('frontend.contact.sendMailContactForm');
Route::get('/san-pham', 'Frontend\FrontendController@product')->name('frontend.product');
Route::get('/gio-hang', 'Frontend\FrontendController@cart')->name('frontend.cart');
Route::post('/dat-hang', 'Frontend\FrontendController@order')->name('frontend.order');
Route::get('/dat-hang/hoan-tat', 'Frontend\FrontendController@orderFinish')->name('frontend.orderFinish');

Route::get('/test', function () {
    $data = DB::select('select * from loai');
    return $data;
});

Route::get('/san-pham/{id}', 'FrontendController@productDetail')->name('frontend.productDetail');
// route Danh mục Sản phẩm
Route::resource('/admin/danhsachsanpham', 'SanPhamController');
// route Danh mục kho
Route::resource('/admin/danhsachkho', 'KhoHangController');

Route::get('/admin/sanpham', 'SanPhamController@index')
        ->middleware('auth')
        ->name('backend.sanpham.index');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/capquyen', function(){
    // $arrPermissions = [];
    // auth()->user()->assignPermissions('quan_tri');
    $user = Nhanvien::find(2);
    $user->givePermissionTo('xem_san_pham');
    $user->givePermissionTo('xuatdulieu_excel_san_pham');
    $user->givePermissionTo('xuatdulieu_pdf_san_pham');
    $user->givePermissionTo('indulieu_san_pham');

    $user2 = Nhanvien::find(3);
    $user2->givePermissionTo('xem_san_pham');
    $user2->givePermissionTo('xuatdulieu_excel_san_pham');
    $user2->givePermissionTo('xuatdulieu_pdf_san_pham');
    $user2->givePermissionTo('indulieu_san_pham');

    $user3 = Nhanvien::find(4);
    $user3->givePermissionTo('xem_san_pham');
    $user3->givePermissionTo('xuatdulieu_excel_san_pham');
    $user3->givePermissionTo('xuatdulieu_pdf_san_pham');
    $user3->givePermissionTo('indulieu_san_pham');

    $user1 = Nhanvien::find(1);
    $user1->givePermissionTo('xem_san_pham');
    $user1->givePermissionTo('them_san_pham');
    $user1->givePermissionTo('sua_san_pham');
    $user1->givePermissionTo('xoa_san_pham');
    $user1->givePermissionTo('xuatdulieu_excel_san_pham');
    $user1->givePermissionTo('xuatdulieu_pdf_san_pham');
    $user1->givePermissionTo('indulieu_san_pham');
    $user1->givePermissionTo('quanly_kho');

    $user4 = Nhanvien::find(100);
    $user4->givePermissionTo('xem_san_pham');
    $user4->givePermissionTo('them_san_pham');
    $user4->givePermissionTo('sua_san_pham');
    $user4->givePermissionTo('xoa_san_pham');
    $user4->givePermissionTo('xuatdulieu_excel_san_pham');
    $user4->givePermissionTo('xuatdulieu_pdf_san_pham');
    $user4->givePermissionTo('indulieu_san_pham');
    $user4->givePermissionTo('quanly_kho');
    

    return 'cap quyen okey';
});
Route::post('/admin/activate/{nv_ma}', 'Backend\BackendController@activate')->name('activate');

Route::get('testMail', function(){
    $dataMail = [];
    $khachhang = Khachhang::find(1);
    $dataMail['khachhang'] = $khachhang->toArray();

    $donhang = Donhang::find(9);
    $dataMail['donhang'] = $donhang->toArray();

    $chitietdonhang = Donhang::where('dh_ma', '=', 9)->first();
    $dataMail['donhang']['chitiet'][] = $chitietdonhang->toArray();

    $sp = Sanpham::find(1);
    $dataMail['donhang']['giohang'][] = $sp;

    Mail::to('kellyfire611@gmail.com')->send(new OrderMailer($dataMail));
});
Route::get('setLocale/{locale}', function ($locale) {
    if (in_array($locale, Config::get('app.locales'))) {
      Session::put('locale', $locale);
    }
    return redirect()->back();
})->name('app.setLocale');

src/khohang/app/Khohang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Khohang extends Model
{
    public    $timestamps   = false;
    protected $table        = 'khohang';
    protected $fillable     = ['kho_ten', 'kho_lienHe', 'kho_diaChi', 'kho_dienThoai', 'kho_quanLy', 'kho_ghiChu'];
    protected $guarded      = ['kho_ma'];
    protected $primaryKey   = 'Kho_ma';
}

src/khohang/app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Nhanvien;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    public function dashboard() {
        return view('backend.dashboard');
    }

    
    public function activate(Request $request, $nv_ma) 
    {
        $nv = Nhanvien::find($nv_ma);
        $nv->nv_trangThai = 2; // Khả dụng
        $nv->save();
        return redirect()->route('home');
    }
}

src/khohang/app/Http/Controllers/KhoHangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\SanPham;
use App\Loai;
use App\Khohang;
use App\Nhanvien;
use App\Hinhanh;
use App\Nhapkho;
use App\Chitietnhapkho;
use App\Xuatkho;
use App\Chitietxuatkho;
use Session;
use Storage;
use App\Exports\SanPhamExport;
use Maatwebsite\Excel\Facades\Excel as Excel;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Support\Facades\Auth;
use Illuminate\Auth\Middleware\Authenticate;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Query\Builder;

class KhoHangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Sử dụng Eloquent Model để truy vấn dữ liệu
    $ds_kho = Khohang::all(); // SELECT * FROM khohang
    // Đường dẫn đến view được quy định như sau: <FolderName>.<ViewName>
    // Mặc định đường dẫn gốc của method view() là thư mục `resources/views`
    // Hiển thị view `backend.sanpham.kho`
    return view('backend.khohang.index')
        // với dữ liệu truyền từ Controller qua View, được đặt tên là `danhsachkho`
        ->with('danhsachkho', $ds_kho);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $ds_kho2 = Khohang::all();
         
         return view('backend.khohang.create')
             // với dữ liệu truyền từ Controller qua View, được đặt tên là `danhsachloai`
             ->with('danhsachkho2', $ds_kho2);
             //->with('danhsachkho', $ds_kho);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $k = new Khohang();
        $k->kho_ten = $request->kho_ten;
        $k->kho_lienHe = $request->kho_lienHe;
        $k->kho_diaChi = $request->kho_diaChi;
        $k->kho_dienThoai = $request->kho_dienThoai;
        $k->kho_quanLy = $request->kho_quanLy;
        $k->kho_ghiChu = $request->kho_ghiChu;

        $k->save();
        Session::flash('alert-info', 'Thêm mới thành công ^^~!!!');
        return redirect()->route('danhsachkho.index'); //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $k = Khohang::where("kho_ma",  $id)->first();
        
        return view('backend.khohang.edit')
            ->with('k', $k);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        $k = Khohang::where("kho_ma",  $id)->first();
        $k->kho_ten = $request->kho_ten;
        $k->kho_lienHe = $request->kho_lienHe;
        $k->kho_diaChi = $request->kho_diaChi;
        $k->kho_dienThoai = $request->kho_dienThoai;
        $k->kho_quanLy = $request->kho_quanLy;
        $k->kho_ghiChu = $request->kho_ghiChu;
        $k->save();
        Session::flash('alert-info', 'Cập nhật thành công ^^~!!!');
        return redirect()->route('danhsachkho.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $k = Khohang::where("kho_ma",  $id)->first();
        $k->delete();
        Session::flash('alert-info', 'Xóa sản phẩm thành công ^^~!!!');
        return redirect()->route('danhsachkho.index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function nhapkho()
    {
        // Sử dụng Eloquent Model để truy vấn dữ liệu
    $ds_nhapkho = Nhapkho::all(); // SELECT * FROM Nhapkho
    $ds_nhanvien = Nhanvien::all();
    return view('backend.khohang.nhapkho')
        // với dữ liệu truyền từ Controller qua View, được đặt tên là `danhsachkho`
        ->with('danhsachnhapkho', $ds_nhapkho)
        ->with('danhsachnhanvien', $ds_nhanvien);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function xuatphieunhap($id)
        {
            $nk = Nhapkho::where("nk_ma",  $id)->first();
            $ctnk = Chitietnhapkho::where("nk_ma",  $id)->first();
            return view('backend.khohang.xuatphieunhap')
                ->with('nk', $nk)
                ->with('ctnk', $ctnk);
        }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function infophieunhap(Request $request, $id)
    {
        $nk = Nhapkho::where("nk_ma",  $id)->first();
        $nk->nk_ngayLapPhieu = $request->nk_ngayLapPhieu;
        $nk->nk_soHoaDon = $request->nk_soHoaDon;
        $nk->nk_hoTenNguoiGiaoHang = $request->nk_hoTenNguoiGiaoHang;
        $nk->nk_lydo = $request->nk_lydo;
        $nk->nv_thuKho = $request->nv_thuKho;
        $nk->nv_nguoiLapPhieu = $request->nv_nguoiLapPhieu; //$nk->nhanviens->nv_hoTen

        $ctnk = Chitietnhapkho::where("nk_ma",  $id)->first();
        $ctnk->sp_ten = $request->sp_ten;
        $ctnk->ctnk_donViTinh = $request->ctnk_donViTinh;
        $ctnk->ctnk_soLuong = $request->ctnk_soLuong;
        $ctnk->ctnk_donGia = $request->ctnk_donGia;
        $ctnk->ctnk_thanhtien = $request->ctnk_thanhtien;
        $ctnk->kho_ma = $request->kho_ma;

        return redirect()->route('backend.khohang.xuatphieunhap');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function xuatkho()
    {
        // Sử dụng Eloquent Model để truy vấn dữ liệu
    $ds_xuatkho = Xuatkho::all(); // SELECT * FROM Nhapkho
    $ds_nhanvien = Nhanvien::all();
    return view('backend.khohang.xuatkho')
        // với dữ liệu truyền từ Controller qua View, được đặt tên là `danhsachkho`
        ->with('danhsachxuatkho', $ds_xuatkho)
        ->with('danhsachnhanvien', $ds_nhanvien);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function phieuxuatkho($id)
     {
        $xk = Xuatkho::where("xk_ma",  $id)->first();
        $ctxk = Chitietxuatkho::where("xk_ma",  $id)->first();
        return view('backend.khohang.phieuxuatkho')
            ->with('xk', $xk)
            ->with('ctxk', $ctxk);
     }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function infophieuxuat(Request $request, $id)
    {
        $xk = Xuatkho::where("xk_ma",  $id)->first();
        $xk->xk_ngayLapPhieu = $request->xk_ngayLapPhieu;
        $xk->xk_soHoaDon = $request->xk_soHoaDon;
        $xk->xk_hoTenNguoiNhan = $request->xk_hoTenNguoiNhan;
        $xk->xk_diaChi = $request->xk_diaChi;
        $xk->xk_lydo = $request->xk_lydo;
        $xk->nv_thuKho = $request->nv_thuKho;
        $xk->nv_nguoiLapPhieu = $request->nv_nguoiLapPhieu; //$nk->nhanviens->nv_hoTen
        $xk->nk_ngayLapPhieu = $request->nk_ngayLapPhieu;

        $ctxk = Chitietxuatkho::where("xk_ma",  $id)->first();
        $ctxk->sp_ma = $request->sp_ma;
        $ctxk->ctxk_donViTinh = $request->ctxk_donViTinh;
        $ctxk->ctnk_soLuong = $request->ctnk_soLuong;
        $ctxk->ctxk_donGia = $request->ctxk_donGia;
        $ctxk->ctxk_thanhtien = $request->ctxk_thanhtien;
        $ctnk->kho_ma = $request->kho_ma;

        return redirect()->route('backend.khohang.phieuxuatkho');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function baocaosoluong()
    {
        $ds_chitietnk = Chitietnhapkho::join('nhapkho as pn', 'chitietnhapkho.nk_ma', '=', 'pn.nk_ma')
                        ->join('khohang as k', 'chitietnhapkho.kho_ma', '=', 'k.kho_ma')
                        ->join('sanpham as sp', 'chitietnhapkho.sp_ten', '=', 'sp.sp_ma')
                        ->select('chitietnhapkho.sp_ten', 'chitietnhapkho.ctnk_donViTinh', DB::raw('count(chitietnhapkho.sp_ten)*chitietnhapkho.ctnk_soLuong as slnhap'), 'chitietnhapkho.ctnk_soLuong', 'chitietnhapkho.ctnk_donGia')
                        ->groupBy('sp.sp_ma')
                        ->orderBy('sp.sp_ten')
                        ->get();
        //$ds_chitietxk = Chitietxuatkho::all();
        $ds_chitietxk = Chitietxuatkho::join('xuatkho as px', 'chitietxuatkho.xk_ma', '=', 'px.xk_ma')
                    ->join('khohang as k', 'chitietxuatkho.kho_ma', '=', 'k.kho_ma')
                    ->join('sanpham as sp', 'chitietxuatkho.sp_ma', '=', 'sp.sp_ma')
                    ->select('chitietxuatkho.sp_ma', 'chitietxuatkho.ctxk_donViTinh', DB::raw('count(chitietxuatkho.sp_ma)*chitietxuatkho.ctxk_soLuong as slxuat'), 'chitietxuatkho.ctxk_soLuong', 'chitietxuatkho.ctxk_donGia')
                    ->groupBy('sp.sp_ma')
                    ->orderBy('sp.sp_ten')
                    // ->havingRaw('count(chitietxuatkho.ctxk_soLuong) = 0')
                    ->get();

         return view('backend.khohang.baocaosoluong')
            ->with('danhsachchitietnk', $ds_chitietnk)
            ->with('danhsachchitietxk', $ds_chitietxk);
    }
}

src/khohang/resources/views/backend/khohang/create.blade.php
@extends('backend.layouts.master')

@section('title')
Thêm mới kho hàng
@endsection

@section('custom-css')
<!-- Các css dành cho thư viện bootstrap-fileinput -->
<link href="{{ asset('vendor/bootstrap-fileinput/css/fileinput.css') }}" media="all" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
<link href="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.css') }}" media="all" rel="stylesheet" type="text/css"/>
@endsection

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form method="post" action="{{ route('danhsachkho.store') }}" enctype="multipart/form-data">
    {{ csrf_field() }}
  
    <div class="form-group">
        <label for="kho_ten">Tên kho hàng</label>
        <input type="text" class="form-control" id="kho_ten" name="kho_ten" value="{{ old('kho_ten') }}">
    </div>
    <div class="form-group">
        <label for="kho_lienHe">Liên Hệ</label>
        <input type="text" class="form-control" id="kho_lienHe" name="kho_lienHe" value="{{ old('kho_lienHe') }}">
    </div>
    <div class="form-group">
        <label for="kho_diaChi">Địa Chỉ</label>
        <input type="text" class="form-control" id="kho_diaChi" name="kho_diaChi" value="{{ old('kho_diaChi') }}">
    </div>
    <div class="form-group">
        <label for="kho_dienThoai">Điện thoại</label>
        <input type="text" class="form-control" id="kho_dienThoai" name="kho_dienThoai" value="{{ old('kho_dienThoai') }}">
    </div>
    <div class="form-group">
        <label for="kho_quanLy">Quản lý</label>
        <input type="text" class="form-control" id="kho_quanLy" name="kho_quanLy" value="{{ old('kho_quanLy') }}">
    </div>
    <div class="form-group">
        <label for="kho_ghiChu">Ghi chú</label>
        <input type="text" class="form-control" id="kho_ghiChu" name="kho_ghiChu" value="{{ old('kho_ghiChu') }}">
    </div>

    <button type="submit" class="btn btn-primary">Lưu</button>
</form>
@endsection

@section('custom-scripts')
<!-- Các script dành cho thư viện bootstrap-fileinput -->
<script src="{{ asset('vendor/bootstrap-fileinput/js/plugins/sortable.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/js/fileinput.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/js/locales/fr.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/themes/fas/theme.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-fileinput/themes/explorer-fas/theme.js') }}" type="text/javascript"></script>

<!-- Các script dành cho thư viện Mặt nạ nhập liệu InputMask -->
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.js') }}"></script>
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('theme/adminlte/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>

<script>
$(document).ready(function(){
    
});
</script>

@endsection

src/khohang/resources/views/backend/khohang/index.blade.php
{{-- View này sẽ kế thừa giao diện từ `backend.layouts.index` --}}
@extends('backend.layouts.master')

{{-- Thay thế nội dung vào Placeholder `title` của view `backend.layouts.index` --}}
@section('title')
Danh sách kho hàng
@endsection

{{-- Thay thế nội dung vào Placeholder `content` của view `backend.layouts.index` --}}
@section('content')
<!-- Đây là div hiển thị Kết quả (thành công, thất bại) sau khi thực hiện các chức năng Thêm, Sửa, Xóa.
- Div này chỉ hiển thị khi trong Session có các key `alert-*` từ Controller trả về. 
- Sử dụng các class của Bootstrap "danger", "warning", "success", "info" để hiển thị màu cho đúng với trạng thái kết quả.
-->
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
      @if(Session::has('alert-' . $msg))
      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
      @endif
    @endforeach
</div>
<!-- Tạo nút Thêm mới sản phẩm 
- Theo quy ước, các route đã được đăng ký trong file `web.php` đều phải được đặt tên để dễ dàng bảo trì code sau này.
- Đường dẫn URL là đường dẫn được tạo ra bằng route có tên `danhsachsanpham.create`
- Sẽ có dạng http://tenmiencuaban.com/admin/danhsachsanpham/create
-->


<a href="{{ route('danhsachkho.create') }}" class="btn btn-primary">Thêm kho mới</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Mã kho</th>
            <th>Tên kho</th>
            <th>Liên hệ</th>
            <th>Địa chỉ</th>
            <th>Điện thoại</th>
            <th>Quản lý</th>
            <th>Ghi chú</th>
            <th>Sửa-Xóa</th>
        </tr>
    </thead>
    <tbody>
     <!-- Sử dụng vòng lặp foreach để duyệt qua các sản phẩm 
        - Biến $danhsachsanpham là biến được truyền qua từ action `index()` trong controller SanPhamController.
        -->
        @foreach($danhsachkho as $k)
            <tr>
                <td>{{ $k->kho_ma }}</td>
                <td>{{ $k->kho_ten }}</td>
                <td>{{ $k->kho_lienHe }}</td>
                <td>{{ $k->kho_diaChi }}</td>
                <td>{{ $k->kho_dienThoai }}</td>
                <td>{{ $k->kho_quanLy }}</td>
                <td>{{ $k->kho_ghiChu }}</td>
                <td>
                    <!-- Tạo nút Sửa sản phẩm 
                    - Theo quy ước, các route đã được đăng ký trong file `web.php` đều phải được đặt tên để dễ dàng bảo trì code sau này.
                    - Đường dẫn URL là đường dẫn được tạo ra bằng route có tên `danhsachsanpham.edit`
                    - Route `danhsachsanpham.edit` cần truyền vào 1 tham số {id}. Giá trị cần truyền là {id} của sản phẩm người dùng cần hiệu chỉnh.
                    - Các tham số cần truyền vào hàm route() là 1 array[]
                    - Sẽ có dạng http://tenmiencuaban.com/admin/danhsachsanpham/{id}/edit
                    -->
                    
                        <a href="{{ route('danhsachkho.edit', ['id' => $k->kho_ma]) }}" class="btn btn-primary pull-left">Sửa</a>
                        

                    <!-- Tạo nút Xóa sản phẩm 
                    - Theo quy ước, các route đã được đăng ký trong file `web.php` đều phải được đặt tên để dễ dàng bảo trì code sau này.
                    - Đường dẫn URL là đường dẫn được tạo ra bằng route có tên `danhsachsanpham.destroy`
                    - Route `danhsachsanpham.destroy` cần truyền vào 1 tham số {id}. Giá trị cần truyền là {id} của sản phẩm người dùng cần xóa.
                    - Các tham số cần truyền vào hàm route() là 1 array[]
                    - Sẽ có dạng http://tenmiencuaban.com/admin/danhsachsanpham/{id}
                    -->
                    
                    <form method="post" action="{{ route('danhsachkho.destroy', ['id' => $k->kho_ma]) }}" class="pull-left">
                    
                        <!-- Khi gởi Request Xóa dữ liệu, Laravel Framework mặc định chỉ chấp nhận thực thi nếu có gởi kèm field `_method=DELETE` -->
                        <input type="hidden" name="_method" value="DELETE" />
                        <!-- Khi gởi bất kỳ Request POST, Laravel Framework mặc định cần có token để chống lỗi bảo mật CSRF 
                        - Bạn có thể tắt đi, nhưng lời khuyên là không nên tắt chế độ bảo mật CSRF đi.
                        - Thay vào đó, sử dụng hàm `csrf_field()` để tự sinh ra 1 input có token dành riêng cho CSRF
                        -->
                        {{ csrf_field() }}                      
                            <button type="submit" class="btn btn-danger">Xóa</button>
                           
                           
                    </form>
                </td>
            </tr>
            @endforeach
    </tbody>
</table>
@endsection